version: 1.0.{build}
image:
- Visual Studio 2019
test: off
skip_branch_with_pr: true
platform:
- x64
build:
  parallel: true
  #cache:
  #- C:\Miniconda-x64\pkgs
  #- C:\Miniconda36-x64\pkgs
environment:
  matrix:
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda37-x64
      BUILD_MODE: Release

  fast_finish: true
install:
- ps: |
    git submodule -q update --init --recursive
- ps: |
      $env:PATH = "$env:MINICONDA;$env:MINICONDA\Scripts;$env:PATH"
      $env:PYTHONHOME = "$env:MINICONDA"
      conda update -y -q conda
      conda install -y -q pytest numpy scipy
build_script:
- set PATH = "%MINICONDA%;%MINICONDA%\Scripts;%PATH%"
- cmake -G "Visual Studio 16 2019" -A "x64" -DCMAKE_SUPPRESS_REGENERATION=1 .
- set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmake --build . --config %BUILD_MODE% -- /v:m /m /logger:%MSBuildLogger%
- pip wheel .


artifacts:
  - path: "mitsuba*.whl"
    name: Wheels

