version: 1.0.{build}
image:
- Visual Studio 2019
- ubuntu1604
test: off
skip_branch_with_pr: true
platform:
- x64
build:
  parallel: true

environment:
  matrix:
  - PYTHON_VERSION: 3.7
    MINICONDA: C:\Miniconda37-x64
  


  fast_finish: true
  TWINE_REPOSITORY_URL:  https://upload.pypi.org/legacy/
  TWINE_USERNAME: __token__

init:


install:
- ps: git submodule -q update --init --recursive
- cmd: |
    set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%
    set PYTHONHOME=%MINICONDA%
    conda update -y -q conda
    conda install -y -q pytest numpy scipy

    
build_script:

#Linux
# Getting python 3 and python dependencies
- sh: sudo apt-get update 
- sh: sudo apt-get install python3
- sh: sudo apt-get -y install python3-pip
- sh: pip3 install pytest numpy scipy
- sh: sudo apt -y install python3-dev
# Getting cmake 3.9
- sh: sudo apt -y purge --auto-remove cmake
- sh: sudo apt-get -y purge cmake
- sh: sudo apt -y install snapd
- sh: sudo snap install cmake --classic 
# Getting C++ dependencies
- sh: sudo apt -y install libc++1 libc++-dev clang-9 libc++1-9 libc++-9-dev libc++abi-9-dev  ninja-build
# Install libraries for image I/O and the graphical user interface 
- sh: sudo apt -y install libz-dev libpng-dev libjpeg-dev libxrandr-dev libxinerama-dev libxcursor-dev
# Compile C++
- sh: export CC=clang-9
- sh: export CXX=clang++-9
- sh: cp ./resources/mitsuba.conf.appveyor .
- sh: cmake -GNinja . 
- sh: ninja
# Create wheel
- sh: pip3 wheel . --wheel-dir=wheelhouse --no-deps

#Windows
- cmd: set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%
- cmd: copy .\resources\mitsuba.conf.appveyor .\mitsuba.conf
- cmd: cmake -G "Visual Studio 16 2019" -A "x64" -DCMAKE_SUPPRESS_REGENERATION=1 ..  -DMTS_OPTIX_PATH="C:\ProgramData\NVIDIA Corporation\OptiX SDK 6.5.0"
- cmd: set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cmd: cmake --build . --config Release -- /v:m /m /logger:%MSBuildLogger%
- cmd: pip wheel . --wheel-dir=wheelhouse --no-deps
#- cmd: pip install twine
#- cmd: twine upload wheelhouse/*

artifacts:
- path: "wheelhouse\\*.whl"
  name: Wheels

